#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : yum-metadata-parser
Version  : 1.1.4
Release  : 11
URL      : http://yum.baseurl.org/download/yum-metadata-parser/yum-metadata-parser-1.1.4.tar.gz
Source0  : http://yum.baseurl.org/download/yum-metadata-parser/yum-metadata-parser-1.1.4.tar.gz
Summary  : A fast YUM meta-data parser
Group    : Development/Tools
License  : GPL-2.0
Requires: yum-metadata-parser-python
BuildRequires : glib-dev
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : pkgconfig(sqlite3)
BuildRequires : python-dev
BuildRequires : setuptools

%description
Fast metadata parser for yum implemented in C.

%package python
Summary: python components for the yum-metadata-parser package.
Group: Default

%description python
python components for the yum-metadata-parser package.


%prep
%setup -q -n yum-metadata-parser-1.1.4

%build
%{__python} setup.py build

%install
rm -rf %{buildroot}
%{__python} setup.py install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
